import { indicatorManageApi } from '/@/api/business/rating/indicator/manage/indicator-manage-api';
import { departmentApi } from '/@/api/system/department-api';
import { employeeApi } from '/@/api/system/employee-api';
export const columns = [
    {
      title: '指标名称',
      dataIndex: 'indicator_name',
      width:200,
    },
    {
      title: '指标编码',
      dataIndex: 'indicator_code',
      width:150,
    },
    {
      title: '采集方式',
      dataIndex: 'cjfs',
      width:100,
      dicData:[
        {
          value:'1',
          label:'自动取数 ',
          color:'green',
        },        
        {
            value:'2',
            label:'手动填报',
            color:'red',
        },    
        {
          value:'',
          label:'未配置',
          color:'',
        },          
      ]
    },
    {
      title: '开展情况',
      dataIndex: 'iskz',
      width:100,
      dicData:[
        {
          value:'0',
          label:'未开展',
          color:'red',
          tag:'1',
        },        
        {
            value:'1',
            label:'已开展',
            color:'green',
            tag:'1',
        }, 
        {
          value:'',
          label:'未配置',
          color:'',
          tag:'1',
        },               
      ]
    },
    {
      title: '分配情况',
      dataIndex: 'isfp',
      width:100,
      dicData:[
        {
          value:'0',
          label:'未分配',
          color:'red',
          tag:'1',
        },        
        {
            value:'1',
            label:'已分配',
            color:'green',
            tag:'1',
        },       
      ]
    },   
    {
      title: '监督科室',
      dataIndex: 's_department',
      width:150,
      showkey:'indicator_code',
      key:'s_department_id',
      type:'select_tree',
      apiUrl:'queryDepartmentTree',
      apiFunc:departmentApi.queryDepartmentTree,
      apiParams:true,
      fieldNames:{ label: 'name', key: 'departmentId', value: 'departmentId', children: 'children' },
      bindName:'s_department',
    },
    {
      title: '监督人',
      dataIndex: 's_person',
      width:100,
      showkey:'indicator_code',
      key:'s_person_id',
      type:'select_tree',
      apiUrl:'queryEmployeeByDeptId',
      apiFunc:employeeApi.queryEmployeeByDeptId,
      apiParams:true,
      fieldNames:{ label: 'actualName', key: 'employeeId', value: 'employeeId', children: 'children' },
      bindName:'s_person',
      valueName:'s_department_id',
      defaultKey:'default_s_person_id',
    }, 
    {
      title: '责任科室',
      dataIndex: 'department',
      width:150,
      showkey:'indicator_code',
      key:'department_id',
      type:'select_tree',
      apiUrl:'queryDepartmentTree',
      apiFunc:departmentApi.queryDepartmentTree,
      apiParams:true,
      fieldNames:{ label: 'name', key: 'departmentId', value: 'departmentId', children: 'children' },
      bindName:'department',
    },    
    {
      title: '责任人',
      dataIndex: 'person',
      width:100,
      showkey:'indicator_code',
      key:'person_id',
      type:'select_tree',
      apiUrl:'queryEmployeeByDeptId',
      apiFunc:employeeApi.queryEmployeeByDeptId,
      apiParams:true,
      fieldNames:{ label: 'actualName', key: 'employeeId', value: 'employeeId', children: 'children' },
      bindName:'person',
      valueName:'department_id',
      defaultKey:'default_person_id',
    },  
    {
      title: '分子指标名称',
      dataIndex: 'indicator_name_fz',
      width:200,
    },
    {
      title: '分子指标编码',
      dataIndex: 'indicator_code_fz',
      width:150,
    },
    {
      title: '分子责任科室',
      dataIndex: 'department_fz',
      width:150,
      showkey:'indicator_code_fz',
      key:'department_fz_id',
      type:'select_tree',
      apiUrl:'queryDepartmentTree',
      apiFunc:departmentApi.queryDepartmentTree,
      apiParams:true,
      fieldNames:{ label: 'name', key: 'departmentId', value: 'departmentId', children: 'children' },
      bindName:'department_fz',
    }, 
    {
      title: '分子责任人',
      dataIndex: 'person_fz',
      width:100,
      showkey:'indicator_code_fz',
      key:'person_fz_id',
      type:'select_tree',
      apiUrl:'queryEmployeeByDeptId',
      apiFunc:employeeApi.queryEmployeeByDeptId,
      apiParams:true,
      fieldNames:{ label: 'actualName', key: 'employeeId', value: 'employeeId', children: 'children' },
      bindName:'person_fz',
      valueName:'department_fz_id',
      defaultKey:'default_person_fz_id',
    },   
    {
      title: '分母指标名称',
      dataIndex: 'indicator_name_fm',
      width:200,
    },
    {
      title: '分母指标编码',
      dataIndex: 'indicator_code_fm',
      width:190,
    },
    {
      title: '分母责任科室',
      dataIndex: 'department_fm',
      width:150,
      showkey:'indicator_code_fm',
      key:'department_fm_id',
      type:'select_tree',
      apiUrl:'queryDepartmentTree',
      apiFunc:departmentApi.queryDepartmentTree,
      apiParams:true,
      fieldNames:{ label: 'name', key: 'departmentId', value: 'departmentId', children: 'children' },
      bindName:'department_fm',
    },  
    {
      title: '分母责任人',
      dataIndex: 'person_fm',
      width:100,
      showkey:'indicator_code_fm',
      key:'person_fm_id',
      type:'select_tree',
      apiUrl:'queryEmployeeByDeptId',
      apiFunc:employeeApi.queryEmployeeByDeptId,
      apiParams:true,
      fieldNames:{ label: 'actualName', key: 'employeeId', value: 'employeeId', children: 'children' },
      bindName:'person_fm',
      valueName:'department_fm_id',
      defaultKey:'default_person_fm_id',
    },   
    {
      title: '操作',
      key: 'operation',
      fixed: 'right',
      width: 80,
      operationData:[{
        type:'link',
        icon:'SnippetsOutlined',
        label:'保存',
        lx:'1',
        click:true,
      }]
    },
];

export const columns_error=[
  {
    title: '指标名称',
    dataIndex: 'indicator_name',
    width:200,
    fixed: 'left',
  },
  {
    title: '指标编码',
    dataIndex: 'indicator_code',
    width:150,
  },
  {
    title: '指标类型',
    dataIndex: 'lx',
    width:100,
    dicData:[
      {
        value:'1',
        label:'比值指标',
        color:'green',
        tag:'1',
      },        
      {
          value:'2',
          label:'分子指标',
          color:'red',
          tag:'1',
      },      
      {
        value:'3',
        label:'分母指标',
        color:'yellow',
        tag:'1',
    },       
    ]
  },   
  {
    title: '监督科室',
    dataIndex: 's_department',
    width:150,    
  },
  {
    title: '监督人',
    dataIndex: 's_person',
    width:100,
  }, 
  {
    title: '责任科室',
    dataIndex: 'department',
    width:150,
  },    
  {
    title: '责任人',
    dataIndex: 'person',
    width:100,
  }, 
  {
    title: '异常说明',
    dataIndex: 'error_info',
    width:190,
    fixed: 'right',
    color:'red',
  },
]

